### ISSUE TITLE
Error thrown when setting dynamic current and vehicle not charging, expected?

### ISSUE THREAD

**Issue by jacoscar** [tmjo/charger-card#67]
I've created an automation that uses the service "set circuit dynamic limit" for my Easee One charger.

I always get this error when executing it with the car is not charging, is this to be expected?

````
Logger: homeassistant.components.automation.limit_dynamic_current
Source: helpers/script.py:525
integration: Automation (documentation, issues)
First occurred: 10:04:46 AM (1 occurrences)
Last logged: 10:04:46 AM

Limit dynamic current: Error executing script. Unexpected error for call_service at pos 3: 'dynamicCircuitCurrentP1'
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 760, in check_circuit_current
    or charger_data.state[compare_p2] != current_p2
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyeasee/utils.py", line 55, in __getitem__
    if type(self._storage[key]) == str and validate_iso8601(self._storage[key]):
            ~~~~~~~~~~~~~^^^^^
KeyError: 'dynamicCircuitCurrentP2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/easee/services.py", line 582, in circuit_execute_set_current
    circuit = controller.check_circuit_current(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/easee/controller.py", line 766, in check_circuit_current
    charger_data.config[compare_p1] != current_p1
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyeasee/utils.py", line 55, in __getitem__
    if type(self._storage[key]) == str and validate_iso8601(self._storage[key]):
            ~~~~~~~~~~~~~^^^^^
KeyError: 'dynamicCircuitCurrentP1
````

**Comment by jacoscar** [comment]
Closed as it'an easee issue, not charging card issue
